data_dir:
  raw: data/raw
  processed: data/processed

pamap2:
  source: https://archive.ics.uci.edu/ml/machine-learning-databases/00231/PAMAP2_Dataset.zip
  destination: pamap2.zip
  train_files: [ 'subject101.dat', 'subject102.dat', 'subject103.dat','subject104.dat', 'subject107.dat', 'subject108.dat', 'subject109.dat' ]
  validation_files: [ 'subject105.dat' ]
  test_files: [ 'subject106.dat' ]
  output_file: 'pamap2_106.h5'
  feature_columns: [ 1, 4, 5, 6, 10, 11, 12, 21, 22, 23, 27, 28, 29, 38, 39, 40, 44, 45, 46 ]
  window_size: 33

opp:
  source: https://archive.ics.uci.edu/ml/machine-learning-databases/00226/OpportunityUCIDataset.zip
  destination: opp.zip
  feature_columns: [ 38, 39, 40, 41, 42, 43, 44, 45, 46, 51, 52, 53, 54, 55, 56, 57, 58, 59, 64, 65, 66, 67, 68, 69, 70, 71, 72, 77, 78, 79, 80, 81, 82, 83, 84, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 250 ]
  train_files: [ 'S1-ADL1.dat', 'S1-ADL3.dat', 'S1-ADL4.dat', 'S1-ADL5.dat', 'S1-Drill.dat', 'S2-ADL1.dat', 'S2-ADL2.dat', 'S2-ADL3.dat', 'S2-Drill.dat', 'S3-ADL1.dat', 'S3-ADL2.dat', 'S3-ADL3.dat', 'S3-Drill.dat', 'S4-ADL1.dat', 'S4-ADL2.dat', 'S4-ADL3.dat', 'S4-ADL4.dat', 'S4-ADL5.dat', 'S4-Drill.dat' ]
  validation_files: [ 'S1-ADL2.dat' ]
  test_files: [ 'S2-ADL4.dat', 'S2-ADL5.dat', 'S3-ADL4.dat', 'S3-ADL5.dat' ]
  window_size: 32

uschad:
  source: http://sipi.usc.edu/had/USC-HAD.zip
  destination: uschad.zip
  train_subject: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
  validation_subject: [ 11, 12 ]
  test_subject: [ 13, 14 ]
  feature_column: [ 'acc_x', 'acc_y', 'acc_z', 'gyr_x', 'gyr_y', 'gyr_z' ]
  label_column: 'activity'
  window_size: 32

skoda:
  source: http://har-dataset.org/lib/exe/fetch.php?media=wiki:dataset:skodaminicp:skodaminicp_2015_08.zip
  destination: skoda.zip
  data_file: data/raw/skoda/SkodaMiniCP_2015_08/right_classall_clean.mat
  window_size: 49