dirs:
  saved_models: ./saved_model

training:
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: [ 'accuracy' ]

pamap2:
  batch_size: 128
  d_model: 128
  dropout: 0.2
  n_head: 4

skoda:
  batch_size: 256
  d_model: 128
  dropout: 0.2
  n_head: 4

opp:
  batch_size: 256
  d_model: 128
  dropout: 0.2
  n_head: 4

uschad:
  batch_size: 256
  d_model: 128
  dropout: 0.2
  n_head: 4
